require "json"

module CrystalUI
  # Generates TypeScript declarations for the frontend from plugin
  # manifests and application @[Command] manifests.
  #
  # Written to `frontend/crystal-ui.d.ts` by the dev asset server on
  # startup, so `CrystalUI.fs.read(...)` etc. get autocomplete in any
  # editor without a build step.
  #
  # Crystal → TypeScript type mapping:
  #   String            → string
  #   Int32 | Int64 | Float64 | Number → number
  #   Bool              → boolean
  #   anything else     → any (JSON::Any, unions, untyped)
  class BindingsGenerator
    @manifests : Array(CommandManifest)

    def initialize(plugins : Array(Plugin), app : Application? = nil)
      @manifests = plugins.map(&.manifest).flat_map(&.values)
      @manifests.concat(app.command_manifests.values) if app
    end

    def self.crystal_type_to_ts(type : String?) : String
      case type
      when "String"                      then "string"
      when "Int32", "Int64", "Float64"   then "number"
      when "Bool"                        then "boolean"
      else                                    "any"
      end
    end

    # Full declaration file contents.
    def typescript : String
      String.build do |io|
        io << "// Auto-generated by CrystalUI. Do not edit.\n"
        io << "// Regenerated on every `crystal-ui dev` start.\n\n"

        io << <<-TS
          interface CrystalBridge {
            postMessage(json: string): void;
          }

          declare namespace CrystalUI {
            function call(name: string, args?: Record<string, any>): Promise<any>;
            function emit(event: string, payload?: any): void;
            function on(event: string, callback: (payload: any) => void): () => void;
            function once(event: string, callback: (payload: any) => void): () => void;

          TS

        # Application @[Command] methods are un-namespaced — expose them
        # as top-level functions on CrystalUI.
        top_level.each do |manifest|
          io << "  function #{manifest.name}(#{ts_args(manifest)}): #{ts_return(manifest)};\n"
        end

        io << "\n" unless top_level.empty?

        namespaces.each do |namespace, commands|
          io << "  namespace #{namespace} {\n"
          commands.each do |command|
            io << "    function #{method_name(command)}(#{ts_args(command)}): #{ts_return(command)};\n"
          end
          io << "  }\n\n"
        end

        io << "  const state: Record<string, any>;\n"
        io << "}\n"
      end
    end

    private def top_level : Array(CommandManifest)
      @manifests.select { |m| !m.name.includes?(".") }
    end

    private def namespaces : Hash(String, Array(CommandManifest))
      grouped = Hash(String, Array(CommandManifest)).new
      @manifests.each do |manifest|
        next if manifest.name.count(".") != 1
        namespace, method = manifest.name.split(".")
        (grouped[namespace] ||= [] of CommandManifest) << manifest
      end
      grouped
    end

    private def method_name(manifest : CommandManifest) : String
      manifest.name.split(".")[-1]
    end

    private def ts_args(manifest : CommandManifest) : String
      return "args?: Record<string, any>" if manifest.args.empty?

      required = manifest.args.reject(&.name.empty?)
      fields = required.map do |arg|
        "#{arg.name}: #{BindingsGenerator.crystal_type_to_ts(arg.type)}"
      end
      # Optional arguments (e.g. `id` on notifications.send) are not
      # distinguished in manifests yet — treat all as required except
      # trailing ones the manifest marks with a `?` suffix in the type.
      "args: { #{fields.join(", ")} }"
    end

    private def ts_return(manifest : CommandManifest) : String
      "Promise<#{BindingsGenerator.crystal_type_to_ts(manifest.returns)}>"
    end
  end
end
